---
title: "R Notebook"
output: html_notebook
---

Rscript -e "rmarkdown::render('DMP_GO_KEGG.Rmd')"

```{r loading packages, message = FALSE, warning = FALSE}
library(data.table)
library(missMethyl)
#library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
library(IlluminaHumanMethylationEPICanno.ilm10b2.hg19)
library(stringr)
```


GO analysis for DMPs (AD-NL)
```{r GO analysis for DMPs (AD-NL)}
# for ad_nl
dmp_ad_nl <- fread("/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/DMP_ad_nl.tsv")

# get significant DMPs
dmp_sig_ad_nl_probe <- (subset(dmp_ad_nl, adj.P.Val < 0.05))$V1

# get all probes
dmp_all_ad_nl_probe <- (dmp_ad_nl)$V1

# get GO terms
gst_ad_nl_go <- gometh(sig.cpg=dmp_sig_ad_nl_probe, all.cpg=dmp_all_ad_nl_probe, collection = "GO", array.type = "EPIC")

# get kegg pathways
gst_ad_nl_kegg <- gometh(sig.cpg=dmp_sig_ad_nl_probe, all.cpg=dmp_all_ad_nl_probe, collection = "KEGG", array.type = "EPIC")
```



```{r GO analysis for DMP overlaps (ad-nl & f & m)}
# read the Venn part file
venn_part_adnl_fm <- fread("/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/venn_f_m_ad_nl_part.csv")

# get the overlap part (17, 61, 25, 1768)
dmp_overlap <- unlist(venn_part_adnl_fm[c(1, 3, 5, 6), 5])
dmp_overlap <- unlist(lapply(dmp_overlap, str_split, "\\|"))

# get GO terms
gst_overlap_go <- gometh(sig.cpg=dmp_overlap, all.cpg=dmp_all_ad_nl_probe, collection = "GO", array.type = "EPIC")

# get kegg pathways
gst_overlap_kegg <- gometh(sig.cpg=dmp_overlap, all.cpg=dmp_all_ad_nl_probe, collection = "KEGG", array.type = "EPIC")
```


Writing the results
```{r writing the results}
# for ad-nl
fwrite(gst_ad_nl_go, "/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/GO_dmp_ad_nl.csv")
fwrite(gst_ad_nl_kegg, "/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/KEGG_dmp_ad_nl.csv")

# for overlaps (ad-nl & f & m)
fwrite(gst_overlap_go, "/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/GO_dmp_adnl_fm_overlap.csv")
fwrite(gst_overlap_kegg, "/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/KEGG_dmp_adnl_fm_overlap.csv")
```

