---
title: "R Notebook"
output: html_notebook
---

Rscript -e "rmarkdown::render('Venn_for_DMPs_erming_adj_plate.Rmd')"

```{r loading packages, message = F}
library(data.table)
library(VennDiagram)
```


Reading DMP results
```{r reading DMP results}
DMP_path <- paste0("/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/", c("DMP_ad_nl.tsv", "DMP_fad_mad.tsv", "DMP_fnl_mnl.tsv", "DMP_fad34_mad34.tsv", "DMP_fnl34_mnl34.tsv", "DMP_fad33_mad33.tsv", "DMP_fnl33_mnl33.tsv", "DMP_fad23_mad23.tsv", "DMP_fnl23_mnl23.tsv"))

DMPs <- lapply(DMP_path, fread)
names(DMPs) <- c("ad_nl", "fad_mad", "fnl_mnl", "fad34_mad34", "fnl34_mnl34", "fad33_mad33", "fnl33_mnl33", "fad23_mad23", "fnl23_mnl23")
```


Subsetting significant DMPs
```{r subsetting significant results}
# subset significantly upregulated DMPs
dmp_sig <- lapply(DMPs, function(df) df[adj.P.Val < 0.05])

# subset significantly upregulated DMPs
dmp_sig_up <- lapply(DMPs, function(df) df[adj.P.Val < 0.05 & logFC > 0])

# subset significantly downregulated DMPs
dmp_sig_down <- lapply(DMPs, function(df) df[adj.P.Val < 0.05 & logFC < 0])
```


Venn diagrams
```{r Venn diagrams}
# venn for f_m_ad_nl
id_f_m_dmp_ad_nl <- list(dmp_sig[[1]]$V1, dmp_sig[[2]]$V1, dmp_sig[[3]]$V1)
names(id_f_m_dmp_ad_nl) <- c("ADvsNL", "F.ADvsM.AD", "F.NLvsM.NL")

venn.diagram(id_f_m_dmp_ad_nl, "/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/id_f_m_dmp_ad_nl.tiff", height = 3000, width = 3000, cat.cex = 0.6, sub.pos = c(0.5, 0.5), fill = c("red", "blue", "green"))
venn_f_m_ad_nl_part <- get.venn.partitions(id_f_m_dmp_ad_nl)


# venn for f_m_ad_nl_up
id_f_m_dmp_ad_nl_up <- list(dmp_sig_up[[1]]$V1, dmp_sig_up[[2]]$V1, dmp_sig_up[[3]]$V1)
names(id_f_m_dmp_ad_nl_up) <- c("ADvsNL_up", "F.ADvsM.AD_up", "F.NLvsM.NL_up")

venn.diagram(id_f_m_dmp_ad_nl_up, "/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/id_f_m_dmp_ad_nl_up.tiff", height = 3000, width = 3000, cat.cex = 0.6, sub.pos = c(0.5, 0.5), fill = c("red", "blue", "green"))
venn_f_m_ad_nl_up_part <- get.venn.partitions(id_f_m_dmp_ad_nl_up)


# venn for f_m_ad_nl_down
id_f_m_dmp_ad_nl_down <- list(dmp_sig_down[[1]]$V1, dmp_sig_down[[2]]$V1, dmp_sig_down[[3]]$V1)
names(id_f_m_dmp_ad_nl_down) <- c("ADvsNL_down", "F.ADvsM.AD_down", "F.NLvsM.NL_down")

venn.diagram(id_f_m_dmp_ad_nl_down, "/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/id_f_m_dmp_ad_nl_down.tiff", height = 3000, width = 3000, cat.cex = 0.6, sub.pos = c(0.5, 0.5), fill = c("red", "blue", "green"))
venn_f_m_ad_nl_down_part <- get.venn.partitions(id_f_m_dmp_ad_nl_down)


# venn for f_m_up_ad_nl_down
id_f_m_up_ad_nl_down <- list(dmp_sig_down[[1]]$V1, dmp_sig_up[[2]]$V1, dmp_sig_up[[3]]$V1)
names(id_f_m_up_ad_nl_down) <- c("ADvsNL_down", "F.ADvsM.AD_up", "F.NLvsM.NL_up")

venn.diagram(id_f_m_up_ad_nl_down, "/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/id_f_m_up_ad_nl_down.tiff", height = 3000, width = 3000, cat.cex = 0.6, sub.pos = c(0.5, 0.5), fill = c("red", "blue", "green"))
venn_f_m_up_ad_nl_down_part <- get.venn.partitions(id_f_m_up_ad_nl_down)


# venn for f_m_down_ad_nl_up
id_f_m_down_ad_nl_up <- list(dmp_sig_up[[1]]$V1, dmp_sig_down[[2]]$V1, dmp_sig_down[[3]]$V1)
names(id_f_m_down_ad_nl_up) <- c("ADvsNL_up", "F.ADvsM.AD_down", "F.NLvsM.NL_down")

venn.diagram(id_f_m_down_ad_nl_up, "/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/id_f_m_down_ad_nl_up.tiff", height = 3000, width = 3000, cat.cex = 0.6, sub.pos = c(0.5, 0.5), fill = c("red", "blue", "green"))
venn_f_m_down_ad_nl_up <- get.venn.partitions(id_f_m_down_ad_nl_up)
```


Writing Venn partitions
```{r writing Venn partitions}
invisible(mapply(fwrite, list(venn_f_m_ad_nl_part, venn_f_m_ad_nl_up_part, venn_f_m_ad_nl_down_part, venn_f_m_up_ad_nl_down_part, venn_f_m_down_ad_nl_up), paste0("/sc/orga/projects/zhangb03a/lei_guo/BM36_methylation_analysis/DMP_Results/DMP_erming_adj_plate/", c("venn_f_m_ad_nl_part.csv", "venn_f_m_ad_nl_up_part.csv", "venn_f_m_ad_nl_down_part.csv", "venn_f_m_up_ad_nl_down_part.csv", "venn_f_m_down_ad_nl_up.csv"))))
```